name: python-gis
channels:
  - conda-forge
  - defaults
dependencies:
  - streamlit=1.10.0=pyhd8ed1ab_1
  - streamlit-folium=0.6.12=pyhd8ed1ab_0
  - pandas=1.4.2=py310hf5e1058_2
  - geopandas=0.10.2=pyhd8ed1ab_1
  - pyproj=3.3.1=py310h1bcc3f4_0
  - folium=0.12.1.post1=pyhd8ed1ab_1
  - pillow=9.0.1=py310hdc2b20a_0

